version: '3.8'

services:
  api:
    image: ligtonribeiro/api-express-example
    container_name: api-express
    ports:
      - 3001:3001
    restart: unless-stopped
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"
    networks:
      - api-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - renderer
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - api-net

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"
    networks:
      - api-net

  fluentbit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluentbit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - loki
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - api-net

networks:
  api-net:
    external: true