name: "CD"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH GCP
        env:
          SSH_USER: ${{ secrets.GCP_SSH_USER }}
          SSH_HOST: ${{ secrets.GCP_SSH_HOST }}
          SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa_gcp
          chmod 600 ~/.ssh/id_rsa_gcp
          cat >> ~/.ssh/config << END
            Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa_gcp
            StrictHostKeyChecking no
          END

      - name: Application deployment
        if: github.ref == 'refs/heads/develop'
        run: ssh google-cloud ./deploy.sh
