name: "Testando API Express"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalação Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalação das dependências
        run: npm install

      - name: Executando a aplicação em um Docker Container
        run: docker run -d -p 3000:3000 --name express-api -v $(pwd):/app -w /app node:16-slim node index.js

      - name: Testando a aplicação
        run: curl http://localhost:3000/hello
