name: "Testando API Express"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalação Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalação das dependências
        run: npm install

      - name: Build
        run: npm run build

      - name: Executando a aplicação em um Docker Container
        run: docker run -d --name express-api -v $(pwd):/app -w /app node:16-slim node dist/server.js

      - name: Instalando cURL
        run: |
          docker exec -i express-api apt-get update
          docker exec -i express-api apt-get install curl -y

      - name: Testando app
        run: docker exec -i express-api curl http://localhost:3000/users | json_pp
